name: Build and Release Pif Paf Pouf Launcher

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pif-paf-pouf-launcher-windows
          path: dist/*.exe
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.yml
          name: Pif Paf Pouf Launcher ${{ github.ref_name }}
          body: |
            🎮 **Nouvelle version du Pif Paf Pouf Launcher !**
            
            ✨ **Améliorations dans cette version :**
            - Auto-connexion au serveur mc301.boxtoplay.com:26327
            - 50+ mods pré-installés automatiquement
            - Shaders Complementary avec settings optimisés
            - Rich Presence Discord avec messages drôles
            - Interface gaming épique avec effets
            - Auto-update intégré pour les futures versions
            
            📥 **Installation :**
            1. Télécharge le fichier .exe
            2. Lance l'installateur
            3. Clique "JOUER" et connecte-toi direct au serveur !
            
            🚀 **Développé avec Claude Code**
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}